import { FC } from 'react'
import { Html, Head, Main, NextScript, DocumentProps } from 'next/document'

const Document: FC<DocumentProps> = () => {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />

        {/* Favicon */}
        <link rel="icon" href="/favicon.ico" />

        {/* Boxicons */}
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />

        {/* Unicons */}
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.8/css/line.css"
        />
      </Head>

      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}

export default Document
